# Generated by Django 4.2.5 on 2023-10-08 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projeto',
            fields=[
                ('proId', models.AutoField(primary_key=True, serialize=False)),
                ('proName', models.CharField(max_length=255)),
                ('proAddress', models.TextField()),
                ('proStatus', models.CharField(max_length=255)),
                ('proCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('proLastUpdate', models.DateTimeField(auto_now=True)),
                ('proStage', models.CharField(max_length=255)),
                ('proGeneralProgress', models.IntegerField()),
                ('proStageProgress', models.IntegerField()),
                ('proNextStageProgress', models.IntegerField()),
                ('proTotalTasks', models.IntegerField()),
                ('proDoneTasks', models.IntegerField()),
                ('proDoingTasks', models.IntegerField()),
                ('proResponsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsaveis', to=settings.AUTH_USER_MODEL)),
                ('proUseCreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projeto',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useType', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Engenheiro'), (3, 'MestreObras'), (4, 'Cliente')], default=4)),
                ('usePhoto', models.TextField()),
                ('useProjects', models.ManyToManyField(blank=True, to='obraBack.projeto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='visualizarProjeto',
            fields=[
                ('visId', models.AutoField(primary_key=True, serialize=False)),
                ('visCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('visProjId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='obraBack.projeto')),
                ('visUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_views', to='obraBack.usuario')),
            ],
            options={
                'db_table': 'visualizarProjeto',
            },
        ),
        migrations.CreateModel(
            name='fotoProjeto',
            fields=[
                ('phoId', models.AutoField(primary_key=True, serialize=False)),
                ('phoBase', models.TextField()),
                ('phoCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('phoProjId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='obraBack.projeto')),
            ],
            options={
                'db_table': 'fotoProjeto',
            },
        ),
        migrations.CreateModel(
            name='dataGrafico',
            fields=[
                ('graId', models.AutoField(primary_key=True, serialize=False)),
                ('graDate', models.DateTimeField(auto_now_add=True)),
                ('graValue', models.FloatField()),
                ('graProjId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_data', to='obraBack.projeto')),
            ],
            options={
                'db_table': 'dataGrafico',
            },
        ),
    ]
