# Generated by Django 4.2.5 on 2023-10-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obraBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='proStage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Planejamento'), (2, 'Projeto Básico'), (3, 'Licenciamento'), (4, 'Mobilização'), (5, 'Fundação'), (6, 'Estrutura'), (7, 'Alvenaria'), (8, 'Telhado'), (9, 'Hidráulica'), (10, 'Elétrica'), (11, 'Revestimento Interno'), (12, 'Revestimento Externo')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='proStatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No Prazo'), (2, 'Concluído'), (3, 'Atrasado')]),
        ),
    ]
