# Generated by Django 4.2.5 on 2023-10-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obraBack', '0002_alter_projeto_prostage_alter_projeto_prostatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usePhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
